-- Migration: Create tiles table for user-specific tile persistence
-- Description: Stores tiles uploaded by users, linked to their Supabase Auth user_id
-- Author: System
-- Date: 2025-10-22

-- Create tiles table
CREATE TABLE IF NOT EXISTS tiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL DEFAULT '',
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add index for faster user-specific queries
CREATE INDEX IF NOT EXISTS idx_tiles_user_id ON tiles(user_id);

-- Add index for ordering by creation time
CREATE INDEX IF NOT EXISTS idx_tiles_created_at ON tiles(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE tiles ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view only their own tiles
CREATE POLICY "Users can view own tiles"
    ON tiles
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can insert their own tiles
CREATE POLICY "Users can insert own tiles"
    ON tiles
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own tiles
CREATE POLICY "Users can update own tiles"
    ON tiles
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own tiles
CREATE POLICY "Users can delete own tiles"
    ON tiles
    FOR DELETE
    USING (auth.uid() = user_id);

-- Add comment to table
COMMENT ON TABLE tiles IS 'User-uploaded tiles that persist across sessions and devices';
COMMENT ON COLUMN tiles.id IS 'Unique tile identifier';
COMMENT ON COLUMN tiles.user_id IS 'Reference to auth.users - owner of this tile';
COMMENT ON COLUMN tiles.name IS 'Optional user-provided name/description for the tile';
COMMENT ON COLUMN tiles.image_url IS 'Supabase Storage URL of the tile image';
COMMENT ON COLUMN tiles.created_at IS 'Timestamp when tile was created';
