-- Migration: Create chats table and add chat_id, kept to generated_images
-- Description: Adds chat functionality for conversational generation
-- Author: System
-- Date: 2025-10-24

-- ============================================
-- CHATS TABLE
-- ============================================

-- Create chats table
CREATE TABLE IF NOT EXISTS chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_chats_user_id ON chats(user_id);
CREATE INDEX IF NOT EXISTS idx_chats_created_at ON chats(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE chats ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view only their own chats
CREATE POLICY "Users can view own chats"
    ON chats
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can insert their own chats
CREATE POLICY "Users can insert own chats"
    ON chats
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own chats
CREATE POLICY "Users can update own chats"
    ON chats
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own chats
CREATE POLICY "Users can delete own chats"
    ON chats
    FOR DELETE
    USING (auth.uid() = user_id);

-- Add comments to table
COMMENT ON TABLE chats IS 'Chat sessions for conversational tile generation';
COMMENT ON COLUMN chats.id IS 'Unique chat identifier';
COMMENT ON COLUMN chats.user_id IS 'Reference to auth.users - owner of this chat';
COMMENT ON COLUMN chats.name IS 'Auto-generated chat name (e.g., "Customer Chat - Oct 24, 2025")';
COMMENT ON COLUMN chats.created_at IS 'Timestamp when chat was created';

-- ============================================
-- UPDATE GENERATED_IMAGES TABLE
-- ============================================

-- Add chat_id column to link generated images to chats
ALTER TABLE generated_images
ADD COLUMN IF NOT EXISTS chat_id BIGINT REFERENCES chats(id) ON DELETE CASCADE;

-- Add kept column to track if user wants to keep this image
ALTER TABLE generated_images
ADD COLUMN IF NOT EXISTS kept BOOLEAN DEFAULT FALSE;

-- Add index for chat-based queries
CREATE INDEX IF NOT EXISTS idx_generated_images_chat_id ON generated_images(chat_id);

-- Add comments to new columns
COMMENT ON COLUMN generated_images.chat_id IS 'Reference to chats - chat session this image belongs to (nullable)';
COMMENT ON COLUMN generated_images.kept IS 'Flag indicating if user wants to keep this image in their catalog';
